---
mongodb_version: "7.0"
mongodb_packages_debian:
  - "mongodb-org={{ mongodb_version }}*"
  - "mongodb-org-server={{ mongodb_version }}*"
  - "mongodb-org-shell={{ mongodb_version }}*"
  - "mongodb-org-mongos={{ mongodb_version }}*"
  - "mongodb-org-tools={{ mongodb_version }}*"
