---
galaxy_info:
  role_name: clickhouse
  author: assignment
  description: Install and start ClickHouse.
  license: MIT
  min_ansible_version: "2.9"
  platforms:
    - name: Debian
      versions:
        - all
    - name: Ubuntu
      versions:
        - all
    - name: EL
      versions:
        - all

dependencies: []
